### PR TITLE
Implement Instrument Serialization

### LINKED ISSUE #17: Handle Seralization/Deserialization of `InstrumentTree`
The point of this is to prove that we can save the full `InstrumentTree` out do disk, and likewise reload it. For the purposes of the prototype, we merely need to prove that the serialization/deserialization aspects of this can be handled. We will not attempt to read-to/from a NeXus file for example

Considerations should also be made for `DetectorInfo`, and `SpectrumInfo` and other information that will be known to the file format.

### PR DESCRIPTION
**Pull request by OwenArnold**
Concept serialization. Fixes #17. The purpose of this PR prototyping is: 

1. To prove that persistence (a [requirement](https://github.com/DMSC-Instrument-Data/documents/tree/master/meeting_notes/April_2016/InstrumentPrototype)) is possible and  serialization 
1. To minimise any aspect of serialization leaking into the domain objects.
1. To use the boost serialization, which is probably the desired route for the boost::mpi serialization.

I have added performance benchmarks. Which I will use to aid future performance enhancements.

### CODE REVIEW

**Comment by OwenArnold** [comment]
Serialization of a 60000 detector SANS instrument takes approximately 1 second on my machine. Deserialization takes the same amount of time.

**Comment by OwenArnold** [comment]
@SimonHeybrock. I realise that this is a big fat PR (sorry!). I think it would be best for me to merge it into the main branch of the prototype rather than you being responsible for inspecting all 80 files.

**Comment by SimonHeybrock** [comment]
@OwenArnold I had started looking into it but then got distracted. Are there specific parts you'd like me to have a look at?

**Comment by OwenArnold** [comment]
@SimonHeybrock. Not really but maybe if you're familiar with it you can help direct the future work. I've added some benchmarks and done some profiling, so I already have some ideas of where to make improvements and how to get things faster. Input always appreciated though.

**Comment by SimonHeybrock** [comment]
@OwenArnold So far I just had a very superficial look:
- You are using `boost::archive::text_oarchive`, why not binary? That might be faster.
- Can you check the size of the serialized output? It would be interesting to get same GB/s numbers.
- Similarely, maybe we could estimate the size of the in-memory instrument. That will yield a theoretical upper bound on the performance (given by the memory bandwidth, and assuming that the instrument does not fit into cache).

**Comment by OwenArnold** [comment]
Yes we could do all of that. Should be quite easy to use some binary archive. @SimonHeybrock we should have a wider talk about the prototype later on this week. I'm keen that we should start drawing it to a conclusion if possible.

**Pull request merged**
