### PR TITLE
Benchmark cow strategy

### PR DESCRIPTION
**Pull request by OwenArnold**
Add benchmark timings for the recursive COW strategy employed in the `InstrumentTree`.

### CODE REVIEW

**Comment by OwenArnold** [comment]
@SimonHeybrock: You might be interested in this benchmark as it demonstrates the advantage of the `InstrumentTree` design when it copes to copies.

```
Benchmark                       Time(ns)    CPU(ns) Iterations
--------------------------------------------------------------
BM_copy_unmodified               4651455    4624971        170                 216.218 items/s 
BM_copy_move_root               13614888   13609784         51                 73.4766 items/s 
BM_copy_move_one_trolley        14275419   14271633         49                 70.0691 items/s 
BM_copy_move_one_bank            6592606    6590191         89                 151.741 items/s 
```
Here's a summary:
* Copies without modification are clearly the fasted thing to do. Only the `Nodes` are copied, but their `cow` `Components` are not.
* Modifying the root node of the tree is the most expensive form of "copy" because of the `Command` has to cascade through the entire `InstrumentTree` (all components) are modified on the copy.
* We then see that modifying only one of the two trolley `Nodes` is less expensive in terms of the copy. That's because the non-child `Node` can leave their `cow` `Components` alone.
* We then see that modifying only on of the four banks of the aforementioned trolley is faster still for the same reasons as above.

**Comment by OwenArnold** [comment]
@SimonHeybrock. I have added the benchmarks with and without the instrument creation to my copy benchmark.

I think the reason that the `trolley` appeared slightly slower than the `root` modification is that whenever a modification is made, the `root` node must always be found first. Commenting that [line](https://github.com/DMSC-Instrument-Data/instrument-prototype/blob/master/cow_instrument/Node.cpp#L22) out and instead just hacking it to `root = this;` and re-running that benchmark. We get these results:

```
BM_copy_unmodified                                             4180587    4178674        193                  239.31 items/s 
BM_copy_move_root_with_instrument_creation_timing             12970374   12958595         42                 77.1689 items/s 
BM_copy_move_one_trolley_with_instrument_creation_timing      11394194   11381732         56                 87.8601 items/s 
BM_copy_move_one_bank_with_instrument_creation_timing          5882539    5878536        140                  170.11 items/s 
BM_copy_move_root_without_instrument_creation_timing          13358355   13355836         55                 74.8736 items/s 
BM_copy_move_one_trolley_without_instrument_creation_timing   10463293   10461732         56                 95.5865 items/s 
BM_copy_move_one_bank_without_instrument_creation_timing       7220181    7219570        107                 138.512 items/s 
```

**Comment by SimonHeybrock** [comment]
The 'without' timings are sometimes longer. Does that imply that within the measurement uncertainty both are identical?

**Comment by OwenArnold** [comment]
@SimonHeybrock Basically Yes. It comes down to the way that I constructed the `StandardInstrument`, the `trolley` `Nodes` aren't doing much. They only hold a `NullComponent uptr` so modifying those is essentially the same as modifying the `root`.

**Pull request merged**
